### ISSUE TITLE
Useless files

### ISSUE THREAD

**Issue by WinterIsPretty** [Saltssaumure/fnf-osu-mania-skin#1]
There are random slider sounds and hitsounds that aren't in osu like hitnormal1 or something

If you want to keep that it's fine however there are also standard files like spinners, and hitnotes that are never going to be used because this is mania only

Also you should add the sound fnf makes when you miss/combo break and die

Also should there be hitsounds in the first place since the hitsounds are the song

**Comment by Saltssaumure** [comment]
Hi there, thanks for posting!

- The numbered hitsounds, eg. hitnormal1, are alternatives for people who prefer them over this skin's default.
- I lightly skinned the osu!standard set so that players who got into osu! through FNF don't get blinded by the default skin.
- Great idea! I'll add this to the to-do list!
- For the FNF hitsounds, unfortunately those don't work very well through a skin. In FNF, each note is tuned to match the song. This isn't possible through an osu! skin, so it would clash with the music.

**Comment by WinterIsPretty** [comment]
I was saying should the hitsounds be empty since fnf doesnt use hitsounds

**Comment by Saltssaumure** [comment]
Ah sorry for misreading. You're right that FNF doesn't have traditional "sharp" hitsounds, because it uses the vocals as hitsounds. I'm going to leave the hitsounds as-is, because without any hitsounds it becomes much more difficult to time keypresses/clicks.
