### ISSUE TITLE
osu!lazer circles are left arrows

### ISSUE THREAD

**Issue by ThatOneCalculator** [Saltssaumure/fnf-osu-mania-skin#11]
Is this normal? It's really distracting, and I can't see the numbers.
![image](https://user-images.githubusercontent.com/44733677/121794013-b4f0cb80-cbb9-11eb-95c9-ea866f8fee1c.png)

**Comment by Saltssaumure** [comment]
Yes that's normal (though not intended). While the default osu! client prioritises animated `hitcircleoverlay-X.png` files over non-animated `hitcircleoverlay.png`, osu!lazer doesn't do so (or at least not for 1-frame animations).

I _probably_ won't be changing the skin to fix this, since this trick allows for a nice skin preview on the default client where the majority of users are. However, here's a manual workaround so it works out on your end:

- Navigate to the skin folder for the default client
- Delete `hitcircleoverlay@2x.png`
- Rename `hitcircleoverlay-0.png` to `hitcircleoverlay.png`, and  `hitcircleoverlay-0@2x.png` to `hitcircleoverlay@2x.png`
- Reimport the skin into osu!lazer

Let me know how you get on with this, and apologies for the inconvenience!

**Comment by ThatOneCalculator** [comment]
That worked :)

Hopefully osu!Lazer will fix this soon
